version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-2404:2024.05.1
    working_directory: ~/laravel-mocktest3

jobs:
  build_and_test:
    executor: machine-executor
    steps:
      - checkout


      # .docker composeのインストール
      - run:
          name: Install Docker Compose
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

      # .envのファイル作成
      - run:
          name: Create .env file from environment variables
          command: |
            echo "DB_CONNECTION=${DB_CONNECTION}" > .env
            echo "DB_HOST=${DB_HOST}" >> .env
            echo "DB_PORT=${DB_PORT}" >> .env
            echo "DB_DATABASE=${DB_DATABASE}" >> .env
            echo "DB_USERNAME=${DB_USERNAME}" >> .env
            echo "DB_PASSWORD=${DB_PASSWORD}" >> .env
            echo "STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}" >> .env
            echo "STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}" >> .env

      # .envの確認
      - run:
          name: Check .env file on host
          command: ls -a

      # .docker composeの起動
      - run:
          name: Start Docker Compose
          command: docker compose -f docker-compose.yml up -d --build

      # MySQLコンテナの起動待ち（10秒待機）
      - run:
          name: Wait for MySQL to start
          command: sleep 10

      # .コンテナの確認
      - run:
          name: List Docker Containers
          command: docker ps


      # .composerのインストール
      - run:
          name: Laravel dependency installation
          command: docker compose exec -T php composer install


      # APP_KEYの生成
      - run:
          name: Generate application key
          command: |
            APP_KEY=$(docker compose exec -T php php artisan key:generate --show)
            echo "APP_KEY=${APP_KEY}" >> .env


      # .envをコンテナ内にコピー
      - run:
          name: Copy .env file from host to container
          command: docker compose cp .env php:/var/www/.env


      # /var/www/の.envの確認
      - run:
          name: Check .env
          command: docker compose exec -T php ls -a /var/www/


      # マイグレーションの実行
      - run:
          name: Run migrations
          command: docker compose exec -T php php artisan migrate --force

      # データベース内のテーブルの確認
      - run:
          name: List MySQL Tables
          command: docker exec -it laravel-mocktest3-mysql-1 mysql -u laravel_user -p'laravel_pass' -e "SHOW TABLES;" laravel_db

      # Mysqlのログの確認
      - run:
          name: Check mysql DataBase
          command: docker logs laravel-mocktest3-mysql-1


      # テストの実行
      - run:
          name: Run PHPUnit tests
          command: docker compose -f docker-compose.yml exec -T php vendor/bin/phpunit --configuration phpunit.xml --stop-on-failure

      # Docker composeの停止
      - run:
          name: Stop Docker Compose
          command: docker compose -f docker-compose.yml down


  deploy:
    executor: machine-executor
    steps:
      - checkout

      # AWS CLIのインストール
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli


      - run:
          name: Deploy to EC2
          command: |
            EC2_INSTANCE_IP="13.115.4.137"
            SSH_KEY="${SSH_KEY}"
            SSH_OPTIONS="-o StrictHostKeyChecking=no -i ${SSH_KEY}"

            ssh ${SSH_OPTIONS} ec2-user@${EC2_INSTANCE_IP} << 'EOF'
          cd /home/ec2-user/laravel-mocktest3 || exit 1
          git pull origin main || exit 1
          docker-compose up -d || exit 1
          EOF





workflows:
  version: 2
  test:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
