version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:8.2
    steps:
      - checkout
      - run:
          name: Install PHP dependencies
          command: composer install --no-interaction --prefer-dist --optimize-autoloader
      - run:
          name: Install Node.js dependencies
          command: npm install
      - run:
          name: Run tests
          command: php artisan test

  deploy:
    docker:
      - image: circleci/php:8.2
    steps:
      - checkout
      - run:
          name: Deploy to EC2
          command: |
            sudo apt-get update
            sudo apt-get install -y rsync
            rsync -avz --exclude '.env' --exclude 'vendor' ./ 52.69.67.231:/home/ec2-user/laravel-mocktest3
            ssh ec2-user@52.69.67.231 "cd /home/ec2-user/laravel-mocktest3 && composer install --no-dev && php artisan migrate --force"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
