version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/php:8.3
    working_directory: ~/project

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - run:
          name: Create symbolic link for default.conf
          command: |
            ln -s ~/project/docker/nginx/default.conf ~/project/default.conf
      - run:
          name: Start Docker Compose
          command: docker compose up -d --build
      - run:
          name: Verify nginx config file exists in container and check permissions
          command: docker compose exec nginx ls -la /etc/nginx/conf.d/
      - run:
          name: List files in /var/www/ inside the container
          command: docker compose exec php ls -la /var/www/
      - run:
          name: Install PHP dependencies
          command: command: docker compose exec php bash -c "cd /var/www && composer install --no-interaction --prefer-dist --optimize-autoloader"
      - run:
          name: Install Node.js dependencies
          command: docker compose exec php npm install
      - run:
          name: Run tests
          command: docker compose exec php php artisan test

  deploy:
    docker:
      - image: cimg/php:8.3
    steps:
      - checkout
      - run:
          name: Deploy to EC2
          command: |
            sudo apt-get update
            sudo apt-get install -y rsync
            rsync -avz --exclude '.env' --exclude 'vendor' ./ ec2-user@52.69.67.231:/home/ec2-user/laravel-mocktest3
            ssh ec2-user@52.69.67.231 "cd /home/ec2-user/laravel-mocktest3 && composer install --no-dev && php artisan migrate --force"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build